# 2.1 数组对象基础

**推荐学习资料：**
《利用python进行数据分析》

## 1. Numpy是什么
1. python语言的一个第三方库
2. 实现了多维数组与矩阵的高效运算
3. 提供了大量的数学函数

官方文档（推荐查看哦！）：
https://www.numpy.org.cn/user/quickstart.html

## 2. 数组对象
* n-dimensional-array(ndarray),多维数组
* 数组（narray）是数组中重要的数据结构
* python中 “万物皆对象”原则，数组同样也是对象，是对象就会有属性和方法

In [1]:
import numpy as np  # 导入包

## 2.1 创建数组
* np.array()__是基本方法
* object, dtype=None ndim =0

In [20]:
import numpy as np  

# 创建一维数组  
a = np.array([0, 1, 2, 3, 4])  
b = np.array((0, 1, 2, 3, 4))  
print(a, type(a))  
print(b, type(b))  

# 创建二维数组  
c = np.array([[11, 12, 13, 14, 15],  
              [16, 17, 18, 19, 20],  
              [21, 22, 23, 24, 25],  
              [26, 27, 28, 29, 30],  
              [31, 32, 33, 34, 35]])  
print(c, type(c))  

# 创建三维数组  
d = np.array([[(1.5, 2, 3), (4, 5, 6)],  
              [(3, 2, 1), (4, 5, 6)]])  
print(d, type(d))  

f = np.array([[(1.5, 2, 3), (4, 5, 6)],  
              [(1.5, 2, 3), (4, 5, 6)],  
              [(1.5, 2, 3), (4, 5, 6)],  
              [(3, 2, 1), (4, 5, 6)]])  
print(f, type(f))  
print(f.shape)
print(f.ndim)

[0 1 2 3 4] <class 'numpy.ndarray'>
[0 1 2 3 4] <class 'numpy.ndarray'>
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <class 'numpy.ndarray'>
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] <class 'numpy.ndarray'>
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] <class 'numpy.ndarray'>
(4, 2, 3)
2


## 2.2 数组元素的类型：
* 组成数组的元素必须是同一个类型
* 某一数组一旦组成，其元素类型是确定的不能随意改变的

In [7]:
data = np.array([1, 2, 3, 4])
print(data.dtype)

int64


## 2.3 修改元素类型
* astype()___数组对象的一个方法
* 根据指定的数组新生成一个数组
* 新数组（new_data）相对于就数组data只有元素的类型不同

In [10]:
data = np.array([1,2 ,3 ,4])
new_data = data.astype(np.float)
print(new_data)
print(type(new_data))
print(new_data.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


## 2.4 数组的属性
* shape
* 返回一个元组
* 其中的元素有整数构成，代表着该数组的形状———每个轴的元素数

In [11]:
data  = np.array([[1, 2, 3, 4],
                [4, 5 ,6 ,7]])
print(data.shape)

(2, 4)


## 2.5 数组的维度
* ndim
* 只有一个轴的数组被称为一维数组
* 返回一个数，代表数组的轴的个数，即维度

In [22]:
data = np.array([[1, 2, 3 ,4],
               [2,3 ,4 ,5]])
print(data.ndim)

data = np.array([[(1,1), (2,2), (3,3) ,(4,4)],
               [(2,2), (3,3), (4,4) ,(5,5)]])
print(data.ndim)

2
3


## 2.6 数组的大小 
* size
* 返回一个整数，代表数组中的元素个数

In [23]:
data = np.array([[1, 2, 3 ,4],
               [2,3 ,4 ,5]])
print(data.size)

8


## 2.7 创建多维数组
* 如果我们传入的是嵌套列表，则得到的一个多维数组

* 嵌套列表的各个元素的长度必须要一致

In [24]:
data = np.array([[1, 2, 3, 4],
                [1, 2 ,3, 4]])
print(data.shape)
print(data.ndim)
print(data.size)

(2, 4)
2
8


## 2.8 函数创建数组
* 通过专门的函数来创建有特征的数组

* 数据比较有规律

* 用元组的形式进行创建

In [25]:
data = np.zeros((2, 3))
data1 = np.ones((2, 3))
print(data1)
print(data)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


## 2.9 Numpy中创建特殊数组的函数

### 2.9.1 arange
* 根据开始值、结束值和步长来创建一个数组(the default start value is 0; the default setp size is 1)

* 通过它创建的是一维数组，数组的元素符合等差数列（结束值-开始值 = 步长值）

* 同于python中常规的“前包括，后不包括”的原则

In [27]:
data = np.arange(1, 10, 3)
data1 = np.arange(4)
print(data)
print(data1)

[1 4 7]
[0 1 2 3]


###  2.9.2 linspace
* 在指定的间隔内返回均匀间隔的数字（得到等差数列）
* np.linspace(start ,stop , num, endpoint = True, retstep = False, dtype =None)
* 不同于python中常规的“前包括，后不包括”的原则
* 可以通过endpoint来调控是否包括末尾的值（default is True）

In [28]:
data = np.linspace(1, 10 ,3)
data1 = np.linspace(1, 10, 3, endpoint = False)
print(data)
print(data1)

[ 1.   5.5 10. ]
[1. 4. 7.]


###  2.9.3 logspace
* 得到的是一个对数等比数列
* np.logspace()返回的是由等比元素组成的数组，等比数列的开始值$base^{start}$  结束值$base^{end}$
* np.logspace(start, stop, num = 50, endpoint = True, base = 10.0, dtype = None)

In [29]:
data = np.logspace(2, 3, 4) #对数的底默认为10
print(data)

[ 100.          215.443469    464.15888336 1000.        ]


###  2.9.4 full  
* 填充一个全部是某个数字的指定形状的数组
* np.full(shape, fill_value, dtype = None)

In [30]:
data = np.full((6,4), 6.4)
print(data)

[[6.4 6.4 6.4 6.4]
 [6.4 6.4 6.4 6.4]
 [6.4 6.4 6.4 6.4]
 [6.4 6.4 6.4 6.4]
 [6.4 6.4 6.4 6.4]
 [6.4 6.4 6.4 6.4]]


### 2.9.5 eye
* 不仅能够创建对角线元素为1的$n*n$元素，还能根据k值调整“对角线”位置

In [31]:
data = np.eye(4, dtype = int ,k = -1)
print(data)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


### 2.9.6 identity
* np.identity()所创建的是一个不能调整“对角线”的单位矩阵
* 输出默认的数据类型是float

In [32]:
data = np.identity(4)
print(data)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###  2.9.7 diag（diagonal line）
* 可以指定对角线元素,还可以根据对角线的个数确定数组各轴的元素

* 也可以调整对角线的位置


In [33]:
data = np.diag([1, 2, 3, 4])
print(data)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [34]:
x = np.arange(9).reshape((3,3)) 
data = np.diag(x)
print(x)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


 ###  2.9.8 fromfuncion
 * 从函数中创建数组
 * np.fromfunction(function, shape **kwargsw)
 * 参数中的function是一个函数对象，shape是创建的数组形状
 * 默认的dtype是float

In [35]:
def foo(x):
    return x+1
print(np.fromfunction(foo, (5,), dtype = int))

[1 2 3 4 5]


In [36]:
print(np.fromfunction(lambda i,j:(i+1)*(j+1), (9,9), dtype = int))

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


END