# 2.2 数组的索引与切片

* 用“序列”的观点来看数组，数组中每个元素都是固定的，可以用“索引”来表示数组中的每个元素

In [2]:
import numpy as np
a = np.arange(12).reshape((2, 2, 3))
print(a)
print(a.shape)
print(a.ndim)  #查看数组的维度

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
3


## 1. 索引
* 可以看到上面我们创建了一个三维数组，规定：按照从外到内每一层是一个轴，从0开始计数，所以第一层就是0轴，第2层就是1轴，第三层就是2轴
* 轴上的元素也是从0开始计数，通过数组上的轴，我们可以操作任意指定方向上的元素

In [3]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [4]:
print(a[1])
a[1][0][0]  #打印元素6

[[ 6  7  8]
 [ 9 10 11]]


6

### 1.1 根据索引取得数组的元素

In [5]:
b = np.linspace(0, 50, 5)   # 创建一个等差数组
b

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [6]:
b[1] #查看12.5

12.5

In [7]:
c = np.logspace(1, 4, 12).reshape(3, 4)
c
# 可以看到0轴上有三个元素，1轴上有四个元素 （一个二维数组）

array([[   10.        ,    18.73817423,    35.11191734,    65.79332247],
       [  123.28467394,   231.01297001,   432.87612811,   811.13083079],
       [ 1519.91108295,  2848.03586844,  5336.69923121, 10000.        ]])

In [8]:
print(c.shape)

(3, 4)


In [9]:
c[1]

array([123.28467394, 231.01297001, 432.87612811, 811.13083079])

In [10]:
c[1, 3]

811.1308307896873

In [11]:
c[1][3]  #c[1, 3]和c[1][3]得到结果相同

811.1308307896873

###  1.2 数组跟列表相同，每个索引对应的值可以通过索引进行修改

In [12]:
b

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [13]:
b[1] = 100
b    #注意是在原数组基础上修改的，所以打印b是修改后的结果

array([  0. , 100. ,  25. ,  37.5,  50. ])

In [14]:
c

array([[   10.        ,    18.73817423,    35.11191734,    65.79332247],
       [  123.28467394,   231.01297001,   432.87612811,   811.13083079],
       [ 1519.91108295,  2848.03586844,  5336.69923121, 10000.        ]])

In [15]:
c[1, 2] = 1
c

array([[1.00000000e+01, 1.87381742e+01, 3.51119173e+01, 6.57933225e+01],
       [1.23284674e+02, 2.31012970e+02, 1.00000000e+00, 8.11130831e+02],
       [1.51991108e+03, 2.84803587e+03, 5.33669923e+03, 1.00000000e+04]])

###  1.3 下标为列表（一维数组）
* 可以看到上面用的是下标为整数，下面来看看下标为列表的形式

In [16]:
d = np.linspace(1, 50, 5)
d

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [17]:
d[0], d[1], d[2]    # 从数组b中取出三个元素
# 如果用 d[0, 1, 2] 显然是会报错的(三维数组索引)

(1.0, 13.25, 25.5)

In [18]:
d[[0, 1, 2]]  # 返回一个数组，对应的是 b[0]，b[1]，b[2]的值

array([ 1.  , 13.25, 25.5 ])

In [19]:
d[[2]]

array([25.5])

#### 可以看到列表作为下标时从原数组中改变了一些元素组成了新数组，这个新数组和原数组相互独立 (从内存来看没有公用一个内存)

In [20]:
e = b[[0, 1, 2]]
e

array([  0., 100.,  25.])

In [21]:
e[1] = 3
e

array([ 0.,  3., 25.])

###  1.4 下标为列表（二维数组）

In [22]:
f = np.linspace(1, 12, 12).reshape(3, 4)
f

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [23]:
f[[0, 2]]

array([[ 1.,  2.,  3.,  4.],
       [ 9., 10., 11., 12.]])

In [24]:
f[[0, 2], [1, 2]]

array([ 2., 11.])

###  1.5 下标是数组
除了整数，列表，还可以是数组

In [25]:
d    #以d为例子

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [26]:
d[np.array([2, 3, 2, 3])]

array([25.5 , 37.75, 25.5 , 37.75])

In [27]:
g= np.logspace(1 ,50, 12).reshape(3, 4)  #创建一个等比数组
g[np.array([1, 2])]

array([[6.57933225e+18, 1.87381742e+23, 5.33669923e+27, 1.51991108e+32],
       [4.32876128e+36, 1.23284674e+41, 3.51119173e+45, 1.00000000e+50]])

## 2. 切片：
* 切片操作是指抽取数组的一部分元素生成新数组。对 python 列表进行切片操作得到的数组是原数组的副本，而对 Numpy 数据进行切片操作得到的数组则是指向相同缓冲区的视图。
*下标和切片都可以从数组中得到部分元素，遵守“前包括， 后不包括”的原则

In [28]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
b = a[2 : 8]
b

array([12, 13, 14, 15, 16, 17])

In [30]:
b[2] = 200
b # 新得到的数组b中的第一个元素的值被修改了

array([ 12,  13, 200,  15,  16,  17])

In [31]:
a  #同时数组a中的元素也得到了改变

array([ 10,  11,  12,  13, 200,  15,  16,  17,  18,  19])



* 通过切边得到的数组和原数组共享了一个内存空间

* 通过索引，得到的是两个不同的数组，占用不同的内存

In [32]:
a = np.arange(10 ,20)
print(a[::2])
print(a[3:])
print(a[::-1])

[10 12 14 16 18]
[13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


#### 对二维或者更多的数组进行切片，也是在一维是基础上进行操作的，分别在每个轴上实施，最终获得合并区域

In [33]:
np.arange(0, 100, 10).reshape(-1, 1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [34]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

In [35]:
b = np.arange(0, 100, 10).reshape(-1, 1) + np.arange(0, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55],
       [60, 61, 62, 63, 64, 65],
       [70, 71, 72, 73, 74, 75],
       [80, 81, 82, 83, 84, 85],
       [90, 91, 92, 93, 94, 95]])

In [36]:
b[1: 4]   # 在0轴方向上切片，得到了按照0轴方向上元素为单元的切片后的数组

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [37]:
print(b[1:4, 2:5])  # 先在0轴方向上“切出一片”，然后在1轴方向上安装[2:5]的要求“切出”

[[12 13 14]
 [22 23 24]
 [32 33 34]]


In [38]:
print(b[0])       # 在0轴方向上切片，得到了按照0轴方向上元素为单元的切片后的数组
print(b[1,:])     

[0 1 2 3 4 5]
[10 11 12 13 14 15]


In [39]:
print(b[:, 2])  #取第三列所有数据
print(b[0:2, 0:2])  #取左上角的四个元素

[ 2 12 22 32 42 52 62 72 82 92]
[[ 0  1]
 [10 11]]


END