# 2.3 运算和通用函数
对整数进行某种运算，在python中不得不使用循环，而Numpy则不需要写循环语句，用更直接的运算符号或者函数就能完成对众多数值的操作

## 1. 基础运算

In [1]:
import numpy as np
lst = [1, 2, 3, 4, 5]
a = np.array(lst)
a*3

array([ 3,  6,  9, 12, 15])

In [2]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
b = a + 10
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [4]:
a -10

array([[-10,  -9,  -8,  -7],
       [ -6,  -5,  -4,  -3],
       [ -2,  -1,   0,   1]])

In [5]:
a/10

array([[0. , 0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6, 0.7],
       [0.8, 0.9, 1. , 1.1]])

### 两个数组进行运算
* 原则上，只有形状一样的数组之间才能进行运算

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [8]:
a.shape == b.shape

True

In [9]:
a + b

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [10]:
a - b

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [11]:
a * b

array([[  0,  11,  24,  39],
       [ 56,  75,  96, 119],
       [144, 171, 200, 231]])

In [12]:
a /b

array([[0.        , 0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     , 0.41176471],
       [0.44444444, 0.47368421, 0.5       , 0.52380952]])

In [13]:
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
m = np.arange(4)
m

array([0, 1, 2, 3])

In [15]:
a + m

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

### 广播机制
广播（Broadcasting）机制描述了 numpy 如何在算术运算期间处理具有不同形状的数组，让较小的数组在较大的数组上“广播”，以便它们具有兼容的形状。并不是所有的维度都要彼此兼容才符合广播机制的要求，但它们必须满足一定的条件。

若两个数组的各维度兼容，也就是两个数组的每一维等长，或其中一个数组为 一维，那么广播机制就适用。如果这两个条件不满足，numpy就会抛出异常，说两个数组不兼容。

总结来说，广播的规则有三个：

* 如果两个数组的维度数dim不相同，那么小维度数组的形状将会在左边补1。
* 如果shape维度不匹配，但是有维度是1，那么可以扩展维度是1的维度匹配另一个数组；
* 如果shape维度不匹配，但是没有任何一个维度是1，则匹配引发错误；

In [16]:
import numpy as np  
# 例1 二维数组加一维数组
x = np.arange(4) 
print(x) 
y = np.ones((3, 4)) 
print(y) 
print(x.shape)  # (4,)  
print(y.shape)  # (3, 4)  

print((x + y).shape)  # (3, 4)  
print(x + y) 

[0 1 2 3]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [17]:
#例2 两个数组均需要广播
x = np.arange(4).reshape(4, 1) 
print(x)  
y = np.ones(5)  
print(y) 
print(x.shape)  # (4, 1)  
print(y.shape)  # (5,)  

print((x + y).shape)  # (4, 5)  
print(x + y)  

[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [19]:
#例1 不匹配报错
x = np.arange(4)  
y = np.ones(5)  

print(x.shape)  # (4,)  
print(y.shape)  # (5,)  

print(x + y)  

(4,)
(5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

## 2. 比较运算和逻辑运算

### 2.1 比较运算

In [20]:
a= np.array([1, 2, 3])
b= np.array([4, 5 ,2])

In [21]:
a>b

array([False, False,  True])

### 2.2 逻辑运算：
* python中有and, or , not 三个逻辑运算符，因为Numpy是第三方库，所以它不能把自己的逻辑运算也用这三个单词命名
* 而是使用logical_and, logical_or, logical_not

In [22]:
a = np.array([3, 6, 9])
b = np.array([4, 5, 8])

*  np.any(a, axis = None, out = None)，a是类数组对象，主要a中(或者指定的轴中)有一个元素是True,则返回True，否则返回False
*  np.all(a, axis = None, out = None), 如果类数组对象a(或指定某个指定的轴中)所有元素都是True，则会返回True，否则返回False

In [23]:
print(np.any(a > b) and np.any(a < b))
print(np.all(a>b))

True
False


## 3. 通用函数
通用函数是能对数组中的每个元素进行操作的函数，即元素级的函数

###  3.1 内置函数
Numpy有一些默认的通用函数，按照参数的个数可将他们进行分类，一个参数的称为一元函数，两个参数称为二元函数
* np.sin, np.cos, np.tan          				 三角函数
* np.arcsin, np.arccos, np.arctan    反三角函数
* np.round                     									 四舍五入
* np.sqrt                     										 求平方根
* np.power                     									指数运算
* np.subtract                    								相减操作
* np.multiply                     							相乘操作
* np.divide                    									 相除操作
* np.floor_divide                    					整除操作
* np.add                      									 相加操作


In [24]:
alpha = np.linspace(-1, 1, 11)   #初始alpha的值
alpha   

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [25]:
y = np.sin(np.pi * alpha)    #计算，并放入sin函数中
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [26]:
np.round(y, decimals = 3)  #四舍五入，保留3位有效数字

array([-0.   , -0.588, -0.951, -0.951, -0.588,  0.   ,  0.588,  0.951,
        0.951,  0.588,  0.   ])

In [27]:
a = np.array([3, 6, 9])
b = np.array([4, 5, 8])
print(a)
print(b)

[3 6 9]
[4 5 8]


In [28]:
np.add(a, b)   # 相加

array([ 7, 11, 17])

In [29]:
np.add(np.power(np.sin(alpha),2), np.power(np.cos(alpha),2))  #（cos^2(x)+sin^2(x)=1）

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.sin(alpha)**2 + np.cos(alpha)**2    #（cos^2(x)+sin^2(x)=1）   

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
a = np.arange(10.0, 100.0,2)        # 初始a的值
b = np.sqrt(a)
b

array([3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262,
       5.47722558, 5.65685425, 5.83095189, 6.        , 6.164414  ,
       6.32455532, 6.4807407 , 6.63324958, 6.78232998, 6.92820323,
       7.07106781, 7.21110255, 7.34846923, 7.48331477, 7.61577311,
       7.74596669, 7.87400787, 8.        , 8.1240384 , 8.24621125,
       8.36660027, 8.48528137, 8.60232527, 8.71779789, 8.83176087,
       8.94427191, 9.05538514, 9.16515139, 9.2736185 , 9.38083152,
       9.48683298, 9.59166305, 9.69535971, 9.79795897, 9.89949494])

In [32]:
np.power(b,2)  #和原来产生的a的值一样

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50., 52., 54., 56., 58., 60.,
       62., 64., 66., 68., 70., 72., 74., 76., 78., 80., 82., 84., 86.,
       88., 90., 92., 94., 96., 98.])

END