### Numpy基础作业

#### 提交作业方式请参考此链接：[<u>如何提交作业<u/>](https://tianchi.aliyun.com/notebook-ai/detail?postId=182576)

### 1.创建一个长度为10的分布在[0,1)一维随机矩阵,然后让第5个元素等于1

In [1]:
import numpy as np

In [6]:
a = np.random.rand(10)
a

array([0.03932506, 0.2483113 , 0.29254022, 0.57074999, 0.84438843,
       0.21415202, 0.3859914 , 0.81779606, 0.43235451, 0.66464961])

In [7]:
a[4]=1
a

array([0.03932506, 0.2483113 , 0.29254022, 0.57074999, 1.        ,
       0.21415202, 0.3859914 , 0.81779606, 0.43235451, 0.66464961])

### 2.创建一个元素为从20到80的长度为10的ndarray对象

In [10]:
a = np.linspace(20,80,10, endpoint = True)
a

array([20.        , 26.66666667, 33.33333333, 40.        , 46.66666667,
       53.33333333, 60.        , 66.66666667, 73.33333333, 80.        ])

### 3.创建一个符合正太分布的长度为10的数组并反转这个数组

In [15]:
a = np.random.randn(10)
print(a)
a = a[::-1]
print(a)

[ 0.56705829  1.19191147  0.60702942 -0.92420255  1.55405523  1.42461139
  0.63931784 -0.29694438 -1.46569923 -0.01956253]
[-0.01956253 -1.46569923 -0.29694438  0.63931784  1.42461139  1.55405523
 -0.92420255  0.60702942  1.19191147  0.56705829]


### 4.随机创建一个4维矩阵，并得到最后两维的和。

In [25]:
#a = np.random.rand(4,4,4,4)  # reshape
a = np.random.randint(2, size=(4,4,4,4))
#print(a,a.ndim)
ax1 = np.sum(a, axis=2)
ax2 = np.sum(a, axis=3)
print(ax1+ax2)
print(ax1)

[[[3 5 4 6]
  [3 2 4 5]
  [6 4 4 4]
  [2 2 5 3]]

 [[6 6 2 4]
  [3 4 4 5]
  [4 5 4 5]
  [6 5 4 5]]

 [[3 3 7 3]
  [4 4 3 5]
  [5 5 5 5]
  [6 4 4 6]]

 [[3 2 5 2]
  [7 7 5 5]
  [5 4 3 4]
  [1 3 3 1]]]
[[[1 3 2 3]
  [1 0 2 4]
  [2 3 1 3]
  [0 1 3 2]]

 [[3 2 1 3]
  [1 3 2 2]
  [2 3 2 2]
  [3 3 2 2]]

 [[1 1 4 2]
  [3 2 2 1]
  [2 2 3 3]
  [3 2 2 3]]

 [[1 1 3 1]
  [3 4 3 2]
  [3 2 2 1]
  [0 2 2 0]]]


### 5.创建一个999999长度的随机数组，使用两种方法对其求三次方，并比较所用时间

### 6.创建一个 5x5 的二维数组，并设置值 1, 2, 3, 4 落在其对角线下方

END