# 📚 2.3相知篇-数据类型

🔲能今天做好的事就不要等到明天。以梦为马，学习趁年华。   
Tensorflow的基本数据类型有：数值型、字符串型和布尔型。

## 一、本节目标
        本节将详述概述Tensorflow2中的数据类型及创建方法，通过实例列举了部分常用的 。

## 二、 数值型

<img src="https://tianchi-public.oss-cn-hangzhou.aliyuncs.com/public/files/forum/161598218325659271615982182129.png">

**注意：** TensorFlow中将以上统称为张量，不作严格区分，可以通过type()函数获得数值的类型，tf.is_tensor()函数判断数值是否是张量。  

**总结 ：**张量是一个多维数组，张量属性包括：ndim(维度)、shape(形状)和dtype(类型)。tf.Tensors对象可以驻留在加速器内存中(如GPU)。TensorFlow提供了丰富的操作库，用于生成和使用张量。

### 2.1 张量创建

张量创建通过tf.constant()来实现。

tf.constant(
    value, dtype=None, shape=None, name='Const'
)

（1）0维

In [7]:
import tensorflow as  tf
#0维
scalar_tf=tf.constant(3.14)
type(scalar_tf),tf.is_tensor(scalar_tf) #查看张量类型及是否是张量

(tensorflow.python.framework.ops.EagerTensor, True)

（2）1维

In [9]:
#1维
vec_tf=tf.constant([3.14,0,1])
type(vec_tf),tf.is_tensor(vec_tf)

(tensorflow.python.framework.ops.EagerTensor, True)

（3）2维

In [5]:
#2维
Max_tf=tf.constant([[3.14,0,1],[6.28,0,2]])
type(Max_tf),tf.is_tensor(Max_tf)

(tensorflow.python.framework.ops.EagerTensor, True)

（4）3维

In [6]:
#3维
Tensor_tf=tf.constant([[[3.14,0,1],[6.28,0,2]],[[1,2,3],[4,5,6]]])
type(Tensor_tf),tf.is_tensor(Tensor_tf)

(tensorflow.python.framework.ops.EagerTensor, True)

显示tensor内容

In [8]:
Tensor_tf

<tf.Tensor: id=6, shape=(2, 2, 3), dtype=float32, numpy=
array([[[3.14, 0.  , 1.  ],
        [6.28, 0.  , 2.  ]],

       [[1.  , 2.  , 3.  ],
        [4.  , 5.  , 6.  ]]], dtype=float32)>

(5）其他方法

In [12]:
import tensorflow as tf
# 创建常量张量，数字后面加个点代表转float32类型
a = tf.constant([[1., 2., 3.], [4., 5., 6.]]) 
a

<tf.Tensor: id=47, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [13]:
# 创建一个shape形状的全为0元素的张量，dtype='tf.float32'为默认，可以自己进行设定。
b = tf.zeros([2,3]) 
b

<tf.Tensor: id=50, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [14]:
# 创建一个全为1元素的张量。
c = tf.ones([2,3])  
c

<tf.Tensor: id=53, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
# 改变张量中元素的数据类型，只能由低精度向高精度转化。
d = tf.cast(c,float)  
d

<tf.Tensor: id=53, shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
# tf.file(dims,value)创建维度为dims，值全为value的张量。
e = tf.fill([2,3],3)   
e

<tf.Tensor: id=56, shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]])>

In [17]:
# 创建一个标准正态分布,shape:形状，mean: 均值，默认是0,stddev: 标准差，默认是1,dtype: 数据类型默认是float32
f = tf.random.normal(shape=(3,2),mean=2,stddev=1,dtype=tf.float32)   
f

<tf.Tensor: id=62, shape=(3, 2), dtype=float32, numpy=
array([[0.9792441 , 2.9201713 ],
       [2.3214788 , 0.60974157],
       [3.7466826 , 1.5505522 ]], dtype=float32)>

In [18]:
# 创建一个截断正态分布,返回一个截断的正态分布，截断标准是标准差的二倍
g = tf.random.truncated_normal(shape=(3,2),mean=2,stddev=1,dtype=tf.float32)  
g

<tf.Tensor: id=68, shape=(3, 2), dtype=float32, numpy=
array([[2.763433 , 2.24438  ],
       [2.1531014, 1.9796753],
       [1.413722 , 3.9397883]], dtype=float32)>

In [19]:
# 创建均匀分布张量，minval为最小值，maxval为最大值
h = tf.random.uniform(shape=(2,3),minval=1,maxval=4,dtype=tf.float32)  
h

<tf.Tensor: id=75, shape=(2, 3), dtype=float32, numpy=
array([[3.3014631, 1.2753613, 3.250054 ],
       [1.5777968, 2.3296537, 2.4439101]], dtype=float32)>

In [20]:
# 随机打乱数组，只打乱第一维元素
i = tf.random.shuffle(a)   
i 

<tf.Tensor: id=76, shape=(2, 3), dtype=float32, numpy=
array([[4., 5., 6.],
       [1., 2., 3.]], dtype=float32)>

In [21]:
# 创建start为起点，delta为变化量，不超过limit的等差张量。
j = tf.range(start=1,limit=5,delta=1,dtype=tf.float32) 
j

<tf.Tensor: id=83, shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

## 三、字符串类型

字符串类型主要用于表示文件的路径；

### 3.1 字符串类型创建

同样字符串类型的创建也是通过tf.constant()来实现。

In [24]:
#字符串创建
String_tf=tf.constant('tensorflow string type')
String_tf

<tf.Tensor: id=85, shape=(), dtype=string, numpy=b'tensorflow string type'>

### 3.2   字符串操作

Tensorflow中，字符串操作通过Tf.strings模块进行的，Tf.strings模块包含了一些常见的字符串处理函数，如拼接join（），长度length（），切分split（）等.

In [25]:
#创建字符串
String_tf=tf.constant('tensorflow string type')
#统计长度
tf.strings.length(String_tf)

<tf.Tensor: id=87, shape=(), dtype=int32, numpy=22>

## 四、布尔类型

TensorFlow的bool类型用于表达比较运算结果；

In [27]:
#bool类型创建
bool_tf = tf.constant(False)
bool_tf

<tf.Tensor: id=89, shape=(), dtype=bool, numpy=False>

## 五、数值精度

对于数值类型的张量有不同字节长度的精度，在创建张量时可以设定其精度如：16bit  32bit 64bit;对应TensorFlow中常用的精度类型有：tf.int16,tf.int32,tf.int64, tf.float16,tf. float 32,tf. float 64(tf.double)。

In [28]:
tf.constant(3.1415926,dtype=tf.double)

<tf.Tensor: id=90, shape=(), dtype=float64, numpy=3.1415926>

### 5.1查看数值精度

通过张量的dtype成员属性查看数值的精度

In [29]:
data_tf=tf.constant(3.1415926)
data_tf.dtype

tf.float32

### 5.2 数值类型转换

Tensorflow中数据转换是通过tf.cast函数实现的

In [30]:
#创建一个张量
data_tf=tf.constant(3.1415926)
#转换其数值精度
data_tf=tf.cast(data_tf,tf.float64)

注意：同python、c++，数据类型转换需要保证合法性；