# 📚 2.5相知篇-数学计算

🔲能今天做好的事就不要等到明天。以梦为马，学习趁年华。

Tensorflow2重新组织了数学计算模块，其提供了数学计算、数值处理的全维度接口，方便了使用者对数据的处理。本部分主要讲解tensorflow2的常用数学计算函数。

## 一、本节目标
        本节将详述讲解tensorflow2的tf.math模块，其提供了常用的基本数学计算、三角计算、复数计算等常用的函数。

## 二、 tf.math模块常用函数列表
Tensorflow提供了丰富的数学计算函数，并将这些函数统一到了tf.math模块中，常用的函数类型如下表所示。

<img src="https://tianchi-public.oss-cn-hangzhou.aliyuncs.com/public/files/forum/161598302540250421615983024305.png"/>

关于数学计算所有的API请学者自行查阅文档：https://tensorflow.google.cn/api_docs/python/tf
从左侧导航栏找到tf.math模块，即可浏览查看所有的数据计算api及其使用方法。

## 三、 基本运算

### 2.2 加减乘除
加法：

tf.math.add(
    x, y, name=None
)

Given two input tensors, the tf.add operation computes the sum for every element in the tensor.   
Both input and output have a range (-inf, inf).   

<img src="https://tianchi-public.oss-cn-hangzhou.aliyuncs.com/public/files/forum/161598320833664891615983207233.png"/>

减法、乘法、除法的参数与加法的类似，在此不再赘述，给出相关的API.  

减法：

tf.math.subtract(
    x, y, name=None
)

乘法：

tf.math.multiply(
    x, y, name=None
)

除法：

tf.math.divide(
    x, y, name=None
)

代码测试：

In [5]:
import tensorflow as tf
# 定义张量常量
a = tf.constant([3,8])
b = tf.constant([2,5])
add = tf.add(a,b)   # 加法
sub = tf.subtract(a,b)   # 减法
mul = tf.multiply(a,b)   # 乘法
div = tf.divide(a,b)   # 除法
print(add)
print('-'*50)
print(sub)
print('-'*50)
print(mul)
print('-'*50)
print(div)

tf.Tensor([ 5 13], shape=(2,), dtype=int32)
--------------------------------------------------
tf.Tensor([1 3], shape=(2,), dtype=int32)
--------------------------------------------------
tf.Tensor([ 6 40], shape=(2,), dtype=int32)
--------------------------------------------------
tf.Tensor([1.5 1.6], shape=(2,), dtype=float64)


### 2.2 指数、开方、对数
指数运算：

tf.math.pow(
    x, y, name=None
)

开方运算：

tf.math.sqrt(
    x, name=None
)

对数运算：

tf.math.log(
    x, name=None
)

代码测试：

In [8]:
a = tf.constant([[1.,2.],[3.,4.]])
# 指数为2
b = tf.pow(a,2)
# 开方 
c = tf.sqrt(b)  
 # 自然指数运算
d = tf.exp(a) 
# 对数运算,以自然常数e为底的对数
e = tf.math.log(a)
# 对各个元素求平方
f = tf.square(a)   
print(b)
print('-'*50)
print(c)
print('-'*50)
print(d)
print('-'*50)
print(e)
print('-'*50)
print(f)

tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[0.        0.6931472]
 [1.0986123 1.3862944]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)


### 2.3矩阵相乘

In [9]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[5,6],[7,8]])
result = tf.matmul(matrix1,matrix2)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
