#  📚 3.10 相恋篇-keras损失函数


         ✅能今天做好的事就不要等到明天。以梦为马，学习趁年华.

----------------------------------------------------------------------------------------------------------------

    损失函数（loss function），可以用来计算输出的结果（预测值）和我们期望的结果（标签）之间的差距，在神经网络的位置如图所示，接下来详细介绍每个函数的作用。

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG963.png"/>

# 一、本节目标
        知道常用损失函数，知道在哪里可以找到损失函数，会自定义损失函数。

# 二、损失函数
  

首先我们要知道损失函数在tensorflow2里面哪个位置，可以看到python3.7/site-packages/tensorflow/keras/losses目录下，

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG964.png"/>

那么损失函数都有哪些呢，可以看到在tensorflow/keras/losses里面有以下损失函数，那么这些函数之间有哪些区别，具体有哪些呢？可以具体参考tensorflow官网。如果本机有tensorflow，可以直接找到

<img src="https://tianchi-public.oss-cn-hangzhou.aliyuncs.com/public/files/forum/161611965570490791616119653388.png"/>


那么在一个机器学习的过程中激活函数在tensorflow2框架中运用在哪个地方呢，
那么损失函数在4.模型训练配置这里面可以使用，

model.compile(
    optimizer=keras.optimizers.RMSprop(),  # Optimizer 优化器
    # Loss function to minimize 损失）
    loss=keras.losses.SparseCategoricalCrossentropy(),
    # List of metrics to monitor 指标
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)那么在tensorflow2.0中这些有哪些差别呢？其实只要懂其中一个损失函数就基本能够理解和使用。

## 2.1 均方差函数(mean_squared_error)
     均方差误差(Mean Squared Error  MSE)函数把输出向量和真实向量映射到笛卡尔坐标系的两个点上，通过计算这两个点之间的欧式距离(准确地说是欧式距离的平方)来衡量两个向量之间的差距:

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG966.png"/>

 MSE 误差函数的值总是大于等于 0，当 MSE 函数达到最小值 0 时，输出等于真实标签， 此时神经网络的参数达到最优状态。均方差广泛应用在回归问题中，在分类问题中也可以应用均方差误差。在 TensorFlow中，可以通过函数方式或层方式实现 MSE 误差计算. 平方差误差损失，用于回归，简写为 mse, 类实现形式为 MeanSquaredError 和 MSE

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG967.png"/>

In [3]:
import tensorflow as tf
o = tf.random.normal([2,10]) # 构造网络输出
print(o)


tf.Tensor(
[[-1.1711771   0.39136323  0.59791994  1.1170292  -1.6079721   0.9971356
   1.785494   -0.58000416 -0.07646657 -0.5593076 ]
 [-1.2421002  -0.45962852  0.4289117  -0.5964178  -0.42673147 -0.82051384
  -0.24469914  0.6017577  -0.34494728  0.3556995 ]], shape=(2, 10), dtype=float32)


In [4]:
y_onehot = tf.constant([1,3]) # 构造真实值 
y_onehot = tf.one_hot(y_onehot, depth=10)
print(y_onehot)


tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(2, 10), dtype=float32)


In [5]:
loss = tf.keras.losses.mse(y_onehot, o) # 计算均方差  平方差误差损失，用于回归，简写为 mse, 类实现形式为 MeanSquaredError 和 MSE
print(loss)

tf.Tensor([1.0770277  0.60094297], shape=(2,), dtype=float32)


## 2.2 交叉熵函数

 <img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG968.png"/>

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG969.png"/>

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG970.png"/>

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG971.png"/>

<img src="http://tianchi-media.oss-cn-beijing.aliyuncs.com/AIlearning/TensorFlow%E8%AF%BE%E7%A8%8B%E5%9B%BE%E7%89%87/%E7%9B%B8%E6%81%8B%E7%AF%87-keras%E6%8D%9F%E5%A4%B1%E5%87%BD%E6%95%B0/WechatIMG972.png"/>

In [6]:
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
loss#可以自己试着计算，看结果 是否相等。

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.05129331, 2.3025851 ], dtype=float32)>

# 三、自定义损失函数

    自定义损失函数只需要定义一个函数，并在compile的时候调用该自定义损失函数即可。损失函数有两个默认参数，分别为实际输出、预测输出，如果损失函数只需要这两个参数，那么设计起来就很方便。  
    
    自定义损失函数有两种情况，一种比较简单，只需要默认参数，不需要加入其它参数，而另一种参数稍显复杂，需要其他的一些参数。

## 3.1 只需要默认参数

In [7]:
#自定义损失函数
def customized_mse(y_true, y_pred):
    return (y_pred - y_true)**2

In [10]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),

])

In [13]:
#编译compile
model.compile(loss = customized_mse,   #使用自定义的损失函数
             optimizer = "sgd", #优化函数
              metrics = ["mean_squared_error"] #评价函数:用于评估当前训练模型的性能,评价函数和损失函数相似，只不过评价函数的结果不会用于训练过程中
             ) 

## 3.2 需要额外的参数

In [14]:
import tensorflow as tf
from tensorflow.keras import activations
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers,models
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Preprocess the data (these are NumPy arrays)
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

y_train = y_train.astype("float32")
y_test = y_test.astype("float32")

# Reserve 10,000 samples for validation
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]
def get_compiled_model():
    model = get_uncompiled_model()
    model.compile(
        optimizer="rmsprop",
        loss="sparse_categorical_crossentropy",
        metrics=["sparse_categorical_accuracy"],
    )
    return model
def get_uncompiled_model():
    inputs = keras.Input(shape=(784,), name="digits")
    x = layers.Dense(64, activation="relu", name="dense_1")(inputs)
    x = layers.Dense(64, activation="relu", name="dense_2")(x)
    outputs = layers.Dense(10, activation="softmax", name="predictions")(x)
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model
class CustomMSE(keras.losses.Loss):
    def __init__(self, regularization_factor=0.1, name="custom_mse"):
        super().__init__(name=name)
        self.regularization_factor = regularization_factor

    def call(self, y_true, y_pred):
        mse = tf.math.reduce_mean(tf.square(y_true - y_pred))
        reg = tf.math.reduce_mean(tf.square(0.5 - y_pred))
        return mse + reg * self.regularization_factor


model = get_uncompiled_model()
model.compile(optimizer=keras.optimizers.Adam(), loss=CustomMSE())

y_train_one_hot = tf.one_hot(y_train, depth=10)
model.fit(x_train, y_train_one_hot, batch_size=64, epochs=1)

782/782 [==============================] - 1s 891us/step - loss: 0.0490


# 四、课后作业

    1 认识其他的损失函数
    2 会自定义损失和调用库中的损失